# Sets default memory used for gradle commands
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Minecraft/Forge versions
minecraft_version=1.12.2
forge_version=14.23.5.2860

## Mod Properties
mod_id=randomloot
mod_name=Random Loot 2
mod_license=All Rights Reserved
mod_version=1.0.0-1.12.2
mod_group_id=dev.marston.randomloot
mod_authors=Marston Connell
mod_description=An RPG style loot system built from the ground up to make Minecraft loot feel more personal.
