blank_issues_enabled: false
contact_links:
 - name: Random Loot Discord
   url: https://discord.gg/w7FDgqB
   about: Join our discord to discuss new features or to discuss behavior that may not be a bug.
 - name: 1.12 or 1.16 issue?
   url: https://github.com/TheMarstonConnell/randomloot/blob/main/SECURITY.md#supported-versions
   about: Random Loot Mod is not being updated for old versions. Please only report issues for 1.20+


   