blank_issues_enabled: false
contact_links:
 - name: Random Loot Discord
   url: https://discord.gg/w7FDgqB
   about: Join our discord to discuss new features or to discuss behavior that may not be a bug.